worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is-testing: true

server-port: 8080

# pg_service_template_db_1 is the service name + _ + filename of the db_1.sql
#dbconnection: 'postgresql://userver:parol@localhost:5432/userver_test' 	#userver_test == db_name
dbconnection: 'postgresql://testsuite@localhost:15433/pg_service_template_db_1'
